sudo: required
language: python
git:
  depth: 3
  quiet: true
python: 
  - '2.7'
matrix:
  include: 
    - python: '2.7'
      env: FAKER_ENV=debug

install:
  - pip install -U cython
  - pip install -r requirements/base.txt

script:
  - make test_simple_server