sudo: required
language: python
git:
  depth: 3
  quiet: true
python: 
  - '2.7'
  - '3.6'
matrix:
  include: 
    - python: '3.6'
      env: FAKER_ENV=debug
    - python: '2.7'
      env: FAKER_ENV=debug

install:
  - pip install -U cython
  - pip install -r requirements/base.txt

script:
  - make start_simple_server
  - python tests/test_simple_server